### ISSUE TITLE
Survicate Integration issue

### ISSUE THREAD

**Issue by Andrew-Samir** [Survicate/survicate-web-surveys-wrapper#3]
![Screenshot 2024-01-03 150257](https://github.com/Survicate/survicate-web-surveys-wrapper/assets/62807873/9d50da5b-d740-4f3e-81bd-8db9da489f7b)

I am integrating Survicate using SDK https://www.npmjs.com/package/@survicate/survicate-web-surveys-wrapper
When i initialize the element it return 404 Not found response

**Comment by janek-j-survicate** [comment]
Hello,
Thank you for reaching out and sharing the screenshot. I noticed that you're attempting to use our package for a Link Survey. Our package is specifically designed for Web Surveys.
